# Generated by Django 5.1.3 on 2024-11-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
